"use client";

import React from "react";
import { Provider as StoreProvider } from "react-redux";
import type { Metadata } from "next";
import "./globals.css";

/* store */
import { store } from "../redux/store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="es" title="LikeShoes">
      <body>
        <StoreProvider store={store}>{children}</StoreProvider>
      </body>
    </html>
  );
};

export default Layout;
